### ISSUE TITLE
Setup needed

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/game-guide#1]
**Goal:** Make it easy to contribute 

- [x] Setup readme explains what this repo does, and how you can contribute without having to download it locally.
- [x] Explain commit process and approval
- [x] List sections needed (@threepwave has PR for this ready)
- [x] Sort index page (default page currently)
?

**Comment by LordSquiddy** [comment]
Need some assets to jazz the index page up
